# Generated by Django 2.1.2 on 2018-12-02 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_chat_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='coupons',
            field=models.ManyToManyField(to='coupons.Coupon'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='userlist',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
