# Generated by Django 2.1.2 on 2018-12-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20181202_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='userlist',
            field=models.ManyToManyField(to='users.BeerBearCustomer'),
        ),
    ]
