# Generated by Django 2.1.2 on 2018-12-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_beerbearcustomer_beerbuddy_receive_list'),
        ('chats', '0005_auto_20181206_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='message',
            name='creator',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='users.BeerBearCustomer'),
        ),
    ]
