# Generated by Django 2.1.2 on 2018-10-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shop_image', models.ImageField(null=True, upload_to='')),
                ('beer_list', models.ManyToManyField(related_name='sale_beershop', to='beers.Beer')),
            ],
        ),
    ]
