# Generated by Django 2.1.2 on 2018-10-29 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beershops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beershop',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beershop',
            name='shop_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
