# Generated by Django 2.1.2 on 2018-12-02 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beers', '0002_auto_20181202_1342'),
        ('beershops', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BeerBearCustomer'),
        ),
        migrations.AddField(
            model_name='beershopreview',
            name='beershop',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='beershops.BeerShop'),
        ),
        migrations.AddField(
            model_name='beershopreview',
            name='creator',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beershop',
            name='beer_list',
            field=models.ManyToManyField(related_name='sale_beershop', to='beers.Beer'),
        ),
        migrations.AddField(
            model_name='beershop',
            name='favorite_user_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_beershop_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beershop',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BeershopOwner'),
        ),
    ]
