# Generated by Django 2.1.2 on 2018-12-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beershops', '0003_auto_20181202_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
