# Generated by Django 2.1.2 on 2018-11-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beershops', '0003_beershopreview_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='beershop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='beershop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
