# Generated by Django 2.1.2 on 2018-12-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beershops', '0004_stamp_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='beershopreview',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
