# Generated by Django 2.1.2 on 2018-12-09 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beershops', '0006_auto_20181209_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beershopreview',
            options={'ordering': ['created_at']},
        ),
    ]
