# Generated by Django 2.1.2 on 2018-12-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_beerbearcustomer_beerbuddy_send_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerbearcustomer',
            name='beerbuddy_receive_list',
            field=models.ManyToManyField(blank=True, related_name='_beerbearcustomer_beerbuddy_receive_list_+', to='users.BeerBearCustomer'),
        ),
    ]
