# Generated by Django 2.1.2 on 2018-11-25 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20181125_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 16, 58, 28, 229401)),
        ),
    ]
