# Generated by Django 2.1.2 on 2018-11-25 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20181125_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 23, 17, 46, 53, 323756)),
        ),
    ]
