# Generated by Django 2.1.2 on 2018-12-06 05:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_beerbearcustomer_beerbuddy_send_list'),
        ('coupons', '0006_auto_20181202_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='coupon',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BeerBearCustomer'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 6, 14, 6, 48, 378188)),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
