# Generated by Django 2.1.2 on 2018-12-09 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_auto_20181209_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 9, 21, 35, 51, 521650)),
        ),
    ]
