# Generated by Django 2.1.2 on 2018-12-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('brewery', models.CharField(max_length=200, null=True)),
                ('style', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('ABV', models.FloatField(null=True)),
                ('IBU', models.IntegerField(null=True)),
                ('EST_CAL', models.IntegerField(null=True)),
                ('avg_scr', models.FloatField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BeerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beer', models.ForeignKey(null=True, on_delete='CASCADE', to='beers.Beer')),
            ],
        ),
    ]
