# Generated by Django 2.1.2 on 2018-12-02 04:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='beerreview',
            name='creator',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beerreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='beers.BeerReview'),
        ),
        migrations.AddField(
            model_name='beer',
            name='favorite_user_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_beer_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
