# Generated by Django 2.1.2 on 2018-12-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_auto_20181202_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='favorite_user_list',
            field=models.ManyToManyField(blank=True, related_name='favorite_beer_list', to='users.BeerBearCustomer'),
        ),
    ]
