# Generated by Django 2.1.2 on 2018-11-09 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_auto_20181104_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerrating',
            name='beer',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='beers.Beer'),
        ),
        migrations.AlterField(
            model_name='beerrating',
            name='creator',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='beer',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='beers.Beer'),
        ),
        migrations.AlterField(
            model_name='beerreview',
            name='creator',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
