# Generated by Django 2.1.2 on 2018-11-25 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beers', '0005_auto_20181109_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beerrating',
            name='beer',
        ),
        migrations.RemoveField(
            model_name='beerrating',
            name='creator',
        ),
        migrations.AddField(
            model_name='beer',
            name='favorite_user_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_beer_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beerreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='beers.BeerReview'),
        ),
        migrations.AddField(
            model_name='beerreview',
            name='score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.DeleteModel(
            name='BeerRating',
        ),
    ]
